
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_SIZE   20
#define COL_WIDTH   5    



//forward declarations
void   print_divider(int size);
void   render_grid(int grid[MAX_SIZE][MAX_SIZE], int size, int highlight);
void   fill_grid(int grid[MAX_SIZE][MAX_SIZE], int size);
void   export_grid(int grid[MAX_SIZE][MAX_SIZE], int size);
void   show_menu(void);
int    get_int(const char *prompt, int min, int max);
void   flush_input(void);



//utility: clear stdin buffer
void flush_input(void) {
    int c;
    while ((c = getchar()) != '\n' && c != EOF);
}



//utility: get an integer from user input, with validation
int get_int(const char *prompt, int min, int max) {
    int val;
    while (1) {
        printf("%s", prompt);
        if (scanf("%d", &val) == 1 && val >= min && val <= max) {
            flush_input();
            return val;
        }
        flush_input();
        printf("  [!] Enter a number between %d and %d.\n", min, max);
    }
}



// Print a horizontal divider line based on grid size
void print_divider(int size) {
    
    int width = 4 + 1 + size * (COL_WIDTH + 1);
    printf("  ");
    for (int i = 0; i < width; i++) putchar('-');
    putchar('\n');
}


void fill_grid(int grid[MAX_SIZE][MAX_SIZE], int size) {
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            grid[i][j] = (i + 1) * (j + 1);
        }
    }
}

//highlight: if highlight > 0, mark multiples of that number with '*'
void render_grid(int grid[MAX_SIZE][MAX_SIZE], int size, int highlight) {
    printf("\n");

   
    printf("  %3s |", "×");
    for (int j = 0; j < size; j++) {
        printf(" %*d", COL_WIDTH, j + 1);
    }
    printf("\n");

    print_divider(size);

    /* ── Data rows ── */
    for (int i = 0; i < size; i++) {
        printf("  %3d |", i + 1);          /* row label */
        for (int j = 0; j < size; j++) {
            int val = grid[i][j];
            if (highlight > 0 && val % highlight == 0) {
                /* Mark multiples — prefix with '*', tighten by 1 char */
                printf(" *%*d", COL_WIDTH - 1, val);
            } else {
                printf(" %*d", COL_WIDTH, val);
            }
        }
        printf("\n");
    }

    print_divider(size);

    if (highlight > 0) {
        printf("  * = multiple of %d\n", highlight);
    }
    printf("\n");
}


void export_grid(int grid[MAX_SIZE][MAX_SIZE], int size) {
    const char *filename = "multiplication_grid.txt";
    FILE *fp = fopen(filename, "w");
    if (!fp) {
        printf("  [!] Could not create '%s'.\n", filename);
        return;
    }

    fprintf(fp, "Multiplication Grid (%dx%d)\n", size, size);
    fprintf(fp, "Generated by SIMS Week 04 — Codex (@codexphere)\n\n");

    //header row
    fprintf(fp, "%4s |", "x");
    for (int j = 0; j < size; j++) fprintf(fp, " %*d", COL_WIDTH, j + 1);
    fprintf(fp, "\n");

    //divider
    int width = 4 + 1 + size * (COL_WIDTH + 1);
    for (int k = 0; k < width; k++) fputc('-', fp);
    fputc('\n', fp);

   //rows
    for (int i = 0; i < size; i++) {
        fprintf(fp, "%4d |", i + 1);
        for (int j = 0; j < size; j++) {
            fprintf(fp, " %*d", COL_WIDTH, grid[i][j]);
        }
        fprintf(fp, "\n");
    }

    fclose(fp);
    printf("  [✓] Grid exported to '%s'.\n", filename);
}

//menu display

void show_menu(void) {
    printf("  ----------------------------------------\n");
    printf("  DYNAMIC MULTIPLICATION GRID  |  Week 04 \n");
    printf("  ----------------------------------------\n");
    printf("  1. Generate grid\n");
    printf("  2. Generate grid with highlight\n");
    printf("  3. Export last grid to .txt\n");
    printf("  4. Exit\n");
    printf("  ----------------------------------------\n");
}

//main program loop

int main(void) {
    int grid[MAX_SIZE][MAX_SIZE];
    int size      = 0;
    int has_grid  = 0;   
    int choice;

    printf("\n  Multiplication Grid \n\n");

    while (1) {
        show_menu();
        choice = get_int("  Choice: ", 1, 4);

        switch (choice) {

          
            case 1:
                size = get_int("  Grid size (1–20): ", 1, MAX_SIZE);
                fill_grid(grid, size);
                render_grid(grid, size, 0);
                has_grid = 1;
                break;

          
            case 2:
                size = get_int("  Grid size (1–20): ", 1, MAX_SIZE);
                fill_grid(grid, size);
                {
                    int max_val = size * size;
                    int h = get_int("  Highlight multiples of (1–n²): ", 1, max_val);
                    render_grid(grid, size, h);
                }
                has_grid = 1;
                break;

            
            case 3:
                if (!has_grid) {
                    printf("  [!] No grid generated yet. Generate one first.\n\n");
                } else {
                    export_grid(grid, size);
                }
                break;

           //exit
            case 4:
                printf("  Goodbye.\n\n");
                return 0;
        }
    }
}